name: Rust Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform:
          - target: aarch64-unknown-linux-musl
          - target: i686-unknown-linux-musl
          - target: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev pkg-config

      - name: Build and test binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
        env:
          CROSS_CONTAINER_OPTS: "-v /var/run/docker.sock:/var/run/docker.sock"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: polipo-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/polipo
          retention-days: 1

  docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest
          platform: linux/amd64,linux/arm64,linux/386
          imageName: ilteoood/polipo
          publish: true
          dockerUser: ilteoood
          dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
